#include "tjsCommHead.h"
#include "CharacterSet.h"
#include "StorageIntf.h"
#include "DebugIntf.h"
#include "UtilStreams.h"
#include "SysInitIntf.h"
#include <string>
#include <map>

typedef struct {
    const char* name;
    const char* start;
    const char* end;
} ResourceEntry;

// generated by cmake/generate_resource_registry.cmake
extern "C" const ResourceEntry resource_table[];
extern "C" const size_t resource_count;

const void* get_binary_resource(int index, size_t* size) {
	if (index >= 0 && index < (int)resource_count) {
		if (size) {
			*size = (size_t)(resource_table[index].end - resource_table[index].start);
		}
		return (const void*)resource_table[index].start;
    }
    if (size) {
        *size = 0;
    }
    return NULL;
}

size_t get_binary_resource_count(void) {
    return resource_count;
}

const char* get_binary_resource_name(size_t index) {
    if (index < resource_count) {
        return resource_table[index].name;
    }
    return NULL;
}

#define MEDIA_NAME TJS_W("resource")

class tTVPResourceStorageMedia : public iTVPStorageMedia
{
	typedef tTVPResourceStorageMedia Self;
	static Self *Instance;

	tjs_int RefCount;
	
	struct ResourceEntry {
		const tjs_uint8* data;
		size_t size;
	};
	
	std::map<std::string, ResourceEntry> resources;
	
	void LoadResources() {
		// resource_registry からリソース一覧を取得
		size_t count = get_binary_resource_count();
		
		for (size_t i = 0; i < count; ++i) {
			const char* name = get_binary_resource_name(i);
			size_t size = 0;
			const void* data = get_binary_resource(i, &size);
			
			if (data && size > 0) {
				ResourceEntry entry;
				entry.data = static_cast<const tjs_uint8*>(data);
				entry.size = size;
				resources[name] = entry;
				
				TVPAddLog(ttstr(TJS_W("Found resource: ")) + ttstr(name));
			}
		}
		
		TVPAddLog(ttstr(TJS_W("Total resources loaded: ")) + ttstr(static_cast<tjs_int>(resources.size())));
	}

	const tjs_uint8* FindData(const ttstr &_name, size_t *size=nullptr) {
		// リソース名を取得
		std::string name;
		TVPUtf16ToUtf8(name, _name.c_str());

		std::string resource_name;
		if (name.size() >= 2 && name[0] == '.' && name[1] == '/') {
			// "./" で始まる場合
			resource_name = name.substr(2);  // "./" の部分を除去
		} else {
			// 名前だけの場合
			resource_name = name.c_str();
		}
		
		// リソースマップから探す
		auto it = resources.find(resource_name);
		if (it != resources.end()) {
			// 見つかった場合はデータとサイズを返す
			if (size) *size = it->second.size;
			return it->second.data;
		}
		
		// 見つからなかった
		if (size) *size = 0;
		return nullptr;
	}

public:
	tTVPResourceStorageMedia() : RefCount(1) {
		LoadResources();
	}

	~tTVPResourceStorageMedia() {
		// resource_registry は静的データなので解放不要
	}

	void TJS_INTF_METHOD  AddRef (void) override { ++RefCount; }
	void TJS_INTF_METHOD  Release(void) override {
		if (RefCount == 1) delete this;
		else --RefCount;
	}

	//--------------------------------------------------------------

	virtual void TJS_INTF_METHOD GetName(ttstr &name) override { name = MEDIA_NAME; }
	virtual void TJS_INTF_METHOD NormalizeDomainName(ttstr &name) override {}
	virtual void TJS_INTF_METHOD NormalizePathName  (ttstr &name) override {}

	virtual bool TJS_INTF_METHOD CheckExistentStorage(const ttstr &name) override {
		return FindData(name) != nullptr;
	}

	virtual iTJSBinaryStream * TJS_INTF_METHOD Open(const ttstr & name, tjs_uint32 flags) override {
		if ((flags & TJS_BS_ACCESS_MASK) != TJS_BS_READ) return nullptr;
		size_t size = 0;
		const tjs_uint8 *data = FindData(name, &size);
		if (!data) return nullptr;
		iTJSBinaryStream *stream = new tTVPMemoryStream(data, static_cast<tjs_uint>(size));
		return stream;
	}

	virtual void TJS_INTF_METHOD GetListAt(const ttstr &name, iTVPStorageLister * lister) override {
		if (name != "" && name != "./") return; // no list

		// リソース一覧をlisterに渡す
		for (const auto& entry : resources) {
			ttstr filename(entry.first.c_str());
			lister->Add(filename);
		}
	}

	virtual void TJS_INTF_METHOD GetLocallyAccessibleName(ttstr &name) override { name.Clear(); } // no local

	//--------------------------------------------------------------

	static void Load() {
		if(!Instance) {
			Instance = new Self();
			TVPRegisterStorageMedia(Instance);
		}
	}
	static void Unload() {
		if (Instance) {
			TVPUnregisterStorageMedia(Instance);
			Instance->Release();
			Instance = nullptr;
		}
	}
};

tTVPResourceStorageMedia * tTVPResourceStorageMedia::Instance = nullptr;

static tTVPAtStart AtStart(TVP_ATSTART_PRI_PREPARE, tTVPResourceStorageMedia::Load);
static tTVPAtExit  AtExit(TVP_ATEXIT_PRI_PREPARE, tTVPResourceStorageMedia::Unload);

